name: Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Use Deno
        uses: denoland/setup-deno@v1
      - name: Build
        run: deno compile --allow-net --allow-read --allow-write --allow-env main.js
      - name: Upload artifacts (Posix)
        uses: actions/upload-artifact@v3
        if: ${{ matrix.os != 'windows' }}
        with:
          name: ${{ runner.os }}
          path: pfc
      - name: Upload artifacts (Windows)
        uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'windows' }}
        with:
          name: ${{ runner.os }}
          path: pfc.exe